language: c

os: linux

jobs: 
  include:
  - dist: bionic
    env: BUILD='debug'
         TEST='mesher'
  - dist: bionic
    env: BUILD='debug'
         TEST='internal_models'
  - dist: bionic
    env: BUILD='debug'
         TEST='external_models'
  - dist: bionic
    env: BUILD='release'
         TEST='mesher'
  - dist: bionic
    env: BUILD='release'
         TEST='internal_models'
  - dist: bionic
    env: BUILD='release'
         TEST='external_models'
  - dist: xenial 
    env: BUILD='debug'

addons:
  apt:
    packages:
      - gfortran 
      - gcc 
      - libopenmpi-dev 
      - libnetcdff-dev 
      - openmpi-bin

before_install:
  - export MINICONDA=$HOME/miniconda
  - export PATH="$MINICONDA/bin:$PATH"
  - export TRAVIS_PYTHON_VERSION=3.8
  - hash -r
  # Install conda only if necessary
  - source "$MINICONDA/etc/profile.d/conda.sh" || { wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
     bash miniconda.sh -b -f -p $MINICONDA; }
  - source "$MINICONDA/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda config --add channels conda-forge
  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION click netcdf4 scipy 
  - conda activate test-environment


install: 
  - ./copytemplates.sh $BUILD
  - make
  
script:
  - if [[ $TEST == 'mesher' ]]; then ./TRAVIS/test_mesher.sh; fi

  - if [[ $TEST == 'internal_models' ]]; then ./submit.py test_prem_ani prem_ani 150.0 --jobtype local --ntheta 2; fi

  - export TEST_DIR=$TRAVIS_BUILD_DIR/TESTING

  - if [[ $TEST == 'external_models' ]]; then 
    cp $TEST_DIR/TEST01_elastic_isotropic/inparam_basic .;
    ./submit.py TEST01 $TEST_DIR/TEST01_elastic_isotropic/model.bm 150.0 --jobtype local --ntheta 2 ;
    fi

  - if [[ $TEST == 'external_models' ]]; then 
    cp $TEST_DIR/TEST02_elastic_anisotropic/inparam_basic .;
    ./submit.py TEST02 $TEST_DIR/TEST02_elastic_anisotropic/model.bm 150.0 --jobtype local --ntheta 2 ;
    fi

  - if [[ $TEST == 'external_models' ]]; then 
    cp $TEST_DIR/TEST03_anelastic_isotropic/inparam_basic .;
    ./submit.py TEST03 $TEST_DIR/TEST03_anelastic_isotropic/model.bm 150.0 --jobtype local --ntheta 2 ;
    fi

  - if [[ $TEST == 'external_models' ]]; then 
    cp $TEST_DIR/TEST04_anelastic_anisotropic/inparam_basic .;
    ./submit.py TEST04 $TEST_DIR/TEST04_anelastic_anisotropic/model.bm 150.0 --jobtype local --ntheta 2 ;
    fi

after_success:

cache:
  apt: true

  directories:
    #- $HOME/travis
    - $HOME/miniconda
